name: nave_fp_uol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  fpdart: ^1.1.1
  dart_mappable: ^4.4.0
  timezone: ^0.10.0
  rxdart: ^0.28.0
  collection: ^1.19.0
  get_it: ^8.0.3
  mixpanel_flutter: ^2.3.4
  auto_route: ^9.3.0+1
  sentry_flutter: ^8.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.1+1
  auto_route_generator: ^9.0.0


flutter:
  uses-material-design: true
