name: nave_fp_uol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1
  firebase_core: ^3.10.1
  sentry_flutter: ^8.9.0
  get_it: ^8.0.3
  mixpanel_flutter: ^2.3.3
  firebase_analytics: ^11.4.1
  intl: ^0.19.0
  cloud_firestore: ^5.6.2
  json_annotation: ^4.9.0
  fpdart: ^1.1.1
  firebase_auth: ^5.4.1
  flutter_bloc: ^9.0.0
  formz: ^0.8.0
  dart_mappable: ^4.3.0
  rxdart: ^0.28.0
  collection: ^1.19.0
  timezone: ^0.10.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  flutter_quill: ^11.0.0
  cloud_functions: ^5.2.0
  video_player: ^2.9.3
  chewie: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: 2.2.3
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.1+1
  auto_route_generator: ^9.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4


flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: KnotIcons
      fonts:
        - asset: assets/fonts/KnotIcons.ttf
