/// Flutter icons KnotIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KnotIcons
///      fonts:
///       - asset: fonts/KnotIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KnotIcons {
  KnotIcons._();

  static const _kFontFam = 'KnotIcons';
  static const String? _kFontPkg = null;

  static const IconData document = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
