// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIWjK0njA5QDK9Ish3GtylGljBBBrjBIQ',
    appId: '1:259722419607:web:9da2e609f075ad511878d2',
    messagingSenderId: '259722419607',
    projectId: 'nave-stg',
    authDomain: 'nave-stg.firebaseapp.com',
    storageBucket: 'nave-stg.firebasestorage.app',
    measurementId: 'G-MBGFVHQSNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyFAx3vCm6uT5LlvBWOdtI-5tR3zkJk0',
    appId: '1:259722419607:android:36e21f85cdb9de981878d2',
    messagingSenderId: '259722419607',
    projectId: 'nave-stg',
    storageBucket: 'nave-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFt-_KEbjN56Q16ay0TVJauuI3wd0ads',
    appId: '1:259722419607:ios:a69ee865ad51b4191878d2',
    messagingSenderId: '259722419607',
    projectId: 'nave-stg',
    storageBucket: 'nave-stg.firebasestorage.app',
    iosBundleId: 'com.example.naveFpUol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvFt-_KEbjN56Q16ay0TVJauuI3wd0ads',
    appId: '1:259722419607:ios:a69ee865ad51b4191878d2',
    messagingSenderId: '259722419607',
    projectId: 'nave-stg',
    storageBucket: 'nave-stg.firebasestorage.app',
    iosBundleId: 'com.example.naveFpUol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIWjK0njA5QDK9Ish3GtylGljBBBrjBIQ',
    appId: '1:259722419607:web:9d3322da873bcdea1878d2',
    messagingSenderId: '259722419607',
    projectId: 'nave-stg',
    authDomain: 'nave-stg.firebaseapp.com',
    storageBucket: 'nave-stg.firebasestorage.app',
    measurementId: 'G-GLLGHTDPBP',
  );
}
